### PR TITLE
Lab IDs fix

### PR DESCRIPTION
**Pull request by sneeze-attack**
This should fix the issues with the lab IDs.

Removes the IDs and values set for them from the bottom of the file and moves them to the locations that match the CleverRaven/CDDA repo. Also uses the values set in the CleverRaven/CDDA repo.

Reference: https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/pull/18

### CODE REVIEW

**Comment by SomeDeadGuy** [comment]
I don't need Rome telling me what to do! I am not gonna change anything.
Everything here, on this git is correct. This is exactly how i want this to be, and how it shall stay. What YOU need to do is take what i have here, and with theese files completely replace everything on main cata repo, exept tileset.txt Only then you gonna have latest version of my tileset on your main repo.
Btw never add or change anything in to my tileset in files on main cata repo, if you do then we gonna have sutuations like this. Make changes in to the game it self, and i am gonna edit my files here as i see fit. If those changes are suddle, or i am not paying attention then contact me here, and i will edit tileset adress those changes. Then, when i made changes here, you will take this tileset from here and update the one what located on main cata repo. Not other way around.

**Comment by sneeze-attack** [comment]
@SomeDeadGuy Wow, fuck me for trying to help.

**Comment by SomeDeadGuy** [comment]
You not helping. You proposing changes, what will remove the ones i am already did. I made custom graphics for those new lab doors. What you want me to do is undo that, and set old graphics for new tiles. I dont want that.

**Comment by sneeze-attack** [comment]
> You not helping. You proposing changes, what will remove the ones i am already did. I made custom graphics for those new lab doors. What you want me to do is undo that, and set old graphics for new tiles. I dont want that.

This would had been useful to know instead of leaving me the reply you did. Do not worry, I will never make the same mistake again.

**Comment by SomeDeadGuy** [comment]
Ohhh, did i hurt your feelings? Good :)
This is how i comunicate with people. If you cant take it, leave it.
And my first post has useful information in it. I repeat, do not do anything to my tileset on main github of cataclysm. Any changes to my tileset will be made here, and then brought to the main repo. Never other way around. Or mess like this will happen.

**Comment by SomeDeadGuy** [comment]
Oohhh you removed your star. :'(
SAD

**Comment by sneeze-attack** [comment]
> I repeat, do not do anything to my tileset on main github of cataclysm.

I'm going to do all sorts of dirty things to your tileset on the main github, I told you not to worry didn't I? ;)

**Comment by SomeDeadGuy** [comment]
*in southern accent* You dirty bastard! Leave my tileset baby alone! You gonna pay for that, sneeze, MARK MY WORDS!

But seriously do what you want with it, it is free for all. Just dont bring conflicting changes here and we are good.

**Comment by SomeDeadGuy** [comment]
"looks on dislikes suddenly appeared on closed hidden PR"
Oh, you went on discord hugbox and cried about it there. :)
tell djur what he can go fuck himself with his hatred of cats

**Comment by itacotaco** [comment]
Your reply was a little over the top, though.

**Comment by SomeDeadGuy** [comment]
Well, this is cause i am little over the top person. ^^
And this is why i do not wanted my tileset in main cata repo. Cause i REALLY do not like people coming in to my house and messing with my stuff, and this is how i react if they do or try to do it.

**Pull request closed without merging**
