### PR TITLE
Added new lab terrain IDs

### PR DESCRIPTION
**Pull request by sneeze-attack**
Changed lab mapgen to use new terrain IDs (to alleviate background tiles not matching floor).
These new terrain IDs need to be added to the tileset_config.json

See https://github.com/CleverRaven/Cataclysm-DDA/pull/28135 for more information

### CODE REVIEW

**Comment by SomeDeadGuy** [comment]
waaaaaat
everything new from labs was added at the day of release
this tileset i maintain, i update it almost every day
i have no power over the ones who updates it in main cata repository

**Comment by sneeze-attack** [comment]
@SomeDeadGuy hmm I checked raw file contents directly from your repo and I can see the new terrain IDs. Not sure why @Pupsi-Mupsi 's PR was stripping the new IDs out. Maybe a rebase was needed before pushing?
I'm thinking at this point maybe this specific PR can be closed and @Pupsi-Mupsi can try rebasing and pushing the changes again?

**Comment by SomeDeadGuy** [comment]
I do wish i knew what all of this means. :)

**Comment by sneeze-attack** [comment]
@SomeDeadGuy I'm new to git too, and I had a hell of a time understanding the different actions/terminology, but I can try and explain what I know.

So basically, if Pupsi forked your repo before you merge the new lab terrain changes in, their repo is going to be out of date. This is what rebasing is for, it pulls in the new changes and then applies your local changes on top of that, that way your files are updated with your latest local changes versus being outdated with the local changes.

As to what happened here to get Pupsi's changes to not include the lab terrain IDs, that I am unsure.

**Comment by Pupsi-Mupsi** [comment]
@sneeze-attack
Nope. My File is exactly the same as the file provided by SomeDeadGuy. 
Download am compare them. But your changes are missing in "both" of them...
https://github.com/Pupsi-Mupsi/Cataclysm-DDA/blob/9d27a9af7e84436039d6571cbda7a19fe6f8c565/gfx/MSX%2B%2BDeadPeopleEdition/tile_config.json

https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/blob/master/MSX%2B%2BDeadPeopleEdition/tile_config.json

**Comment by sneeze-attack** [comment]
@Pupsi-Mupsi  and @SomeDeadGuy I think I see what happened here.

If you check this repo when the new tiles were added in:
https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/commit/18f5cbd4048df0d0cb9dd22ec0df81a6da28c8f7

You can see the adds in the diff, but they are the wrong values and at the end of the file. This is what is mixing everything up, since these IDs were added to the CleverRaven/CDDA repo in a different location in the same file and with different values as seen here:
https://github.com/CleverRaven/Cataclysm-DDA/commit/f53995c0f89a5ba5c9566c7a28d3489349958fc3

At this point to fix this, your tile_config.json should have those IDs removed and the IDs from the CleverRaven/CDDA branch should be used.

**Pull request closed without merging**
